# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleetboard < Formula
  desc "Terminal dashboard for AI coding-plan usage & balance across providers."
  homepage "https://github.com/maybewaityou/fleetboard"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.2.3/fleetboard_darwin_amd64.tar.gz"
      sha256 "f1640f838b894979ef01aa0fcfa37fe8115dc3de826dad528c4e552884a5ced6"

      define_method(:install) do
        bin.install "fleetboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.2.3/fleetboard_darwin_arm64.tar.gz"
      sha256 "b5cb54f18862f6bff29048cf3b0ba5104ea66f7b01ea2bd8aa980b84083513dd"

      define_method(:install) do
        bin.install "fleetboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.2.3/fleetboard_linux_amd64.tar.gz"
      sha256 "87b51b5cb777894952ee79f860d4e0f402f7ed5df957fdb25d87ee21a70a8454"
      define_method(:install) do
        bin.install "fleetboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.2.3/fleetboard_linux_arm64.tar.gz"
      sha256 "dde91e655101b1b2a55f131798d5144d328d56e0ae603af0bfc007000fbf2d50"
      define_method(:install) do
        bin.install "fleetboard"
      end
    end
  end

  test do
    system "#{bin}/fleetboard", "--help"
  end
end
