# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleetboard < Formula
  desc "Terminal dashboard for AI coding-plan usage & balance across providers."
  homepage "https://github.com/maybewaityou/fleetboard"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.1.0/fleetboard_darwin_amd64.tar.gz"
      sha256 "77ab565f091905639e271db527186b7e9b26195d0ecc5c07058f4595ce2b7fcd"

      define_method(:install) do
        bin.install "fleetboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.1.0/fleetboard_darwin_arm64.tar.gz"
      sha256 "4f8fea40cdfae208944809107c813aadafeb7bd99eb424f154c5adfec8879b63"

      define_method(:install) do
        bin.install "fleetboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.1.0/fleetboard_linux_amd64.tar.gz"
      sha256 "fddb9922e090a7e968c4979d99ff717d81f75c9e77595d6b8e7c504c84f1e680"
      define_method(:install) do
        bin.install "fleetboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/fleetboard/releases/download/v0.1.0/fleetboard_linux_arm64.tar.gz"
      sha256 "5808c56ad2786ff59ba537e37d73957ef5ce4ae700651d293bebf7b1cd7e4f3c"
      define_method(:install) do
        bin.install "fleetboard"
      end
    end
  end

  test do
    system "#{bin}/fleetboard", "--help"
  end
end
