# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytmux < Formula
  desc "Terminal-based interactive tmux session manager, inspired by lazyssh."
  homepage "https://github.com/maybewaityou/lazytmux"
  version "0.1.12"
  license "Apache-2.0"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybewaityou/lazytmux/releases/download/v0.1.12/lazytmux_darwin_amd64.tar.gz"
      sha256 "0d8ea62011a6efefbbcf3f4010cabf6b39b780c1ffb1795fed8c5dbb52000765"

      define_method(:install) do
        bin.install "lazytmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybewaityou/lazytmux/releases/download/v0.1.12/lazytmux_darwin_arm64.tar.gz"
      sha256 "7b3b05190d25d380b922810aa04ef602faed86697540dfd93fcc9353a4e3b9ef"

      define_method(:install) do
        bin.install "lazytmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/lazytmux/releases/download/v0.1.12/lazytmux_linux_amd64.tar.gz"
      sha256 "8f494b5339a43d8639f6e1c5b03fb3c2bfa6815feaf3119a28b3cb7dd32d2d75"
      define_method(:install) do
        bin.install "lazytmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybewaityou/lazytmux/releases/download/v0.1.12/lazytmux_linux_arm64.tar.gz"
      sha256 "a327db213975d6ae02055a0dec81a5f41715ef8053c7818298ee63e4f7e4be6e"
      define_method(:install) do
        bin.install "lazytmux"
      end
    end
  end

  test do
    system "#{bin}/lazytmux", "--help"
  end
end
